
#   ~.twitter_keys.yaml in root directory should look something like this 



search_tweets_premium:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/30day/dev.json
  bearer_token: <your bearer_token>
  consumer_key: "<your-consumer-key"
  consumer_secret: "<your-consumer-secret>"
