from alpine:latest

RUN apk add --no-cache python3-dev \
RUN apk add --no-cache gcc \
    && pip3 install --upgrade pip

WORKDIR /app

COPY . /app

RUN pip3 --no-cache-dir install -r requirements.txt                                                                            

EXPOSE 5000

ENTRYPOINT  ["python3"]

CMD ["parse_json.py"]